name: "CI/CD - Mobile"

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./godot/Papyrus/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: ''

    - name: Install required Android SDK packages
      run: |
        sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"

    - name: Create keytore file for signing APK
      run: |
        mkdir -p $HOME/.android/
        keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
        mv debug.keystore $HOME/.android/

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
        unzip Godot_v4.2.1-stable_linux.x86_64.zip

    - name: Download Godot Export Templates
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        mkdir -v -p ~/.local/share/godot/export_templates/4.2.1.stable/
        unzip Godot_v4.2.1-stable_export_templates.tpz
        mv ./templates/* ~/.local/share/godot/export_templates/4.2.1.stable/

    - name: Use custom editor settings for Godot
      run: |
        mkdir -p ~/.config/godot
        mv ./editor-settings-gh-actions.tres ~/.config/godot/editor_settings-4.tres

    - name: Export Game
      run: |
        # run editor once in headless mode to import assets
        ./Godot_v4.2.1-stable_linux.x86_64 --headless --editor --quit-after 2

        # run the export for android
        mkdir -v -p ../../builds/android/
        ./Godot_v4.2.1-stable_linux.x86_64 --headless --export-debug Android ../../builds/android/Papyrus.apk

    - name: Download butler
      run: |
        # Download butler
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler

        # Verify butler installation
        ./butler -V

    - name: Deploy to itch.io
      run: |
        # Push to itch.io
        ./butler push ../../builds/android/Papyrus.apk tonloco/papyrus:android-alpha
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}