name: "CI/CD - Mobile"

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./godot/Papyrus/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_linux.x86_64.zip
        unzip Godot_v4.1.3-stable_linux.x86_64.zip

    - name: Download Godot Export Templates
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_export_templates.tpz
        mkdir -v -p ~/.local/share/godot/export_templates/4.1.3.stable/
        unzip Godot_v4.1.3-stable_export_templates.tpz
        mv ./templates/* ~/.local/share/godot/export_templates/4.1.3.stable/

    - name: Export Game
      run: |
        mkdir -v -p ../../builds/android/
        ./Godot_v4.1.3-stable_linux.x86_64 --headless --export-debug Android ../../builds/android/Papyrus.apk