name: Run DB Migrations

on:
  workflow_dispatch:
    inputs:
      migration_command:
        description: 'Migration Command'
        required: true
        type: choice
        options:
          - 'upgrade'
          - 'downgrade'
        default: 'upgrade'
      revision:
        description: 'Revision ID'
        required: true
        default: 'head'

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install alembic psycopg2-binary

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create and populate .env file
        run: |
          # get connection details for postgres db
          DB_ID=$(doctl databases list | grep papyrus-db | awk '{print $1}')
          DB_DATA_JSON=$(doctl databases get $DB_ID --output json)
          PG_PUBLIC_URI=$(echo $DB_DATA_JSON | jq -r .[].connection.uri)

          # create .env file with secrets
          cat <<EOF > .env
          PG_URI="$PG_PUBLIC_URI"
          EOF

      - name: Run Alembic Migration
        env:
          MIGRATION_COMMAND: ${{ github.event.inputs.migration_command }}
          REVISION: ${{ github.event.inputs.revision }}
        run: |
          alembic $MIGRATION_COMMAND $REVISION
